### ISSUE TITLE
OPK missing from 1.99

### ISSUE THREAD

**Issue by dogboydog** [DrUm78/picodrive-irixxxx#4]
Hello,

Users are asking about how to get the opk: 
https://github.com/DrUm78/picodrive-irixxxx/releases

![image](https://user-images.githubusercontent.com/9920963/146384788-b559c491-492a-47cc-9ce1-9e2a7b8d9e77.png)

Please update with the opk if you can. Thank you

**Comment by DrUm78** [comment]
Not planned for now.
